name: Update RSS JSON

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 06:00 UTC (≈09:00 МСК, ≈01:00 America/Chicago)
  workflow_dispatch:

permissions:
  contents: write

# не запускаем параллельные ранны одного и того же workflow
concurrency:
  group: update-rss-json
  cancel-in-progress: false

jobs:
  build:
    # запускаем только из основной ветки (поменяй, если у тебя не main)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # если файлы не в корне, раскомментируй и укажи папку
    # working-directory: ./scripts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # будем использовать GITHUB_TOKEN явно

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install feedparser

      - name: Run RSS to JSON script
        run: python rss_to_json.py

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes (only if changed)
        run: |
          git add episodes.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update episodes.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
