name: Update RSS JSON

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install feedparser

      - name: Generate episodes.json
        run: python rss_to_json.py

      # Если episodes.json не изменился — можно пропустить деплой (опционально)
      - name: Detect changes
        id: diff
        run: |
          git add episodes.json
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Prepare Pages artifact
        if: steps.diff.outputs.changed == 'true'
        run: |
          mkdir -p ./public
          cp episodes.json ./public/
          # положи сюда index.html, если нужен
      - name: Upload artifact
        if: steps.diff.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    if: needs.build.outputs.changed != 'false'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
