name: Update RSS JSON

on:
  schedule:
    - cron: '0 6 * * *'   # каждый день в 06:00 UTC (≈09:00 МСК, ≈01:00 Chicago)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install feedparser

      - name: Generate episodes.json
        run: python rss_to_json.py

      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp episodes.json public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
